# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('yomigana', models.CharField(max_length=50)),
                ('height', models.IntegerField()),
                ('threeSize', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('cv', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('image', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
