# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idol',
            name='birthday',
            field=models.CharField(max_length=20),
        ),
    ]
