# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 14:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20170802_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idol',
            old_name='image',
            new_name='og_image',
        ),
    ]
