# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20170802_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idol',
            name='og_image',
        ),
    ]
