# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20170802_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idol',
            name='image',
            field=models.ImageField(default='', upload_to='idol/'),
        ),
    ]
